// Shared readers for the skill folders. Used by the catalog generator and the
// site build, so both parse a skill the same way.

import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const unquote = (v) => v.replace(/^["']|["']$/g, '').trim();

// Minimal frontmatter reader. The spec allows only scalars and a flat metadata
// map, so a full YAML parser would be more surface than the format needs.
export function frontmatter(source) {
  // A file that went through a Windows checkout or a zip can carry CRLF. Read it as LF.
  const src = source.replace(/\r\n?/g, '\n');
  if (!src.startsWith('---')) return { data: {}, body: src };
  const end = src.indexOf('\n---', 3);
  if (end === -1) return { data: {}, body: src };
  const raw = src.slice(4, end);
  const body = src.slice(end + 4).replace(/^\n/, '');
  const data = {};
  let mapKey = null;
  for (const line of raw.split('\n')) {
    if (!line.trim()) continue;
    const nested = line.match(/^\s+([A-Za-z0-9_-]+):\s*(.*)$/);
    if (nested && mapKey) {
      data[mapKey][nested[1]] = unquote(nested[2]);
      continue;
    }
    const m = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!m) continue;
    if (m[2] === '') { mapKey = m[1]; data[mapKey] = {}; }
    else { mapKey = null; data[m[1]] = unquote(m[2]); }
  }
  return { data, body };
}

// Triggers are written into the description as: Triggers: 'a', 'b', 'c'.
// The separator is matched loosely. A skill that writes "Triggers," instead of
// "Triggers:" is following the convention in spirit, and silently dropping its
// whole trigger list is worse than accepting a comma. validate.sh warns when the
// canonical form is not used.
//
// The list can sit early, with more text after it. It ends at the first quote followed by a
// full stop. Everything else, before and after the list, is the summary.
export function splitDescription(desc = '') {
  const i = desc.search(/Triggers?\s*[:,—-]/i);
  if (i === -1) return { summary: desc.trim(), triggers: [] };
  const tail = desc.slice(i);
  const end = tail.search(/'\.(\s|$)/);
  const list = end === -1 ? tail : tail.slice(0, end + 2);
  const after = end === -1 ? '' : tail.slice(end + 2);
  const triggers = [...list.matchAll(/'([^']+)'/g)].map((m) => m[1]);
  const summary = `${desc.slice(0, i).trim()} ${after.trim()}`.trim();
  return { summary, triggers };
}

// "Requires ffmpeg, and yt-dlp for URL sources." -> ['ffmpeg', 'yt-dlp']
// "Git Bash" is the Windows fallback for a bash script, not a dependency on git.
export function deps(compat = '') {
  const found = new Set();
  for (const m of compat.matchAll(/\b(ffmpeg|yt-dlp|python|node|uv|git(?!\s+bash)|docker|jq|pandoc|imagemagick)\b/gi)) {
    found.add(m[1].toLowerCase());
  }
  return [...found];
}

// The public address of the site. Anything an agent keeps for later, such as the Latest line
// in a changelog, points here and not at a path in the repository, so it survives a re-layout.
export const SITE_URL = 'https://agent-toolkit.itqanlab.com';

// Every item lives in plugins/<name>/. A plugin keeps its skill in skills/<skill>/, which is the
// shape Codex requires and the one Claude Code and the open standard already accept. The skill
// folder is what every other agent installs, so it carries its own README and CHANGELOG.
//
//   plugins/<name>/.claude-plugin/plugin.json     written by hand
//   plugins/<name>/.codex-plugin/plugin.json      generated by scripts/build-catalog.mjs
//   plugins/<name>/skills/<skill>/SKILL.md        the skill
export function readPlugins(root) {
  const dir = join(root, 'plugins');
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => {
      const pluginRoot = join(dir, e.name);
      const manifestPath = join(pluginRoot, '.claude-plugin', 'plugin.json');
      const skillsDir = join(pluginRoot, 'skills');
      const skills = existsSync(skillsDir)
        ? readdirSync(skillsDir, { withFileTypes: true })
          .filter((s) => s.isDirectory() && existsSync(join(skillsDir, s.name, 'SKILL.md')))
          .map((s) => {
            const base = join(skillsDir, s.name);
            return { name: s.name, base, fm: frontmatter(readFileSync(join(base, 'SKILL.md'), 'utf8')).data };
          })
        : [];
      return {
        name: e.name,
        root: pluginRoot,
        manifest: existsSync(manifestPath) ? JSON.parse(readFileSync(manifestPath, 'utf8')) : null,
        skills,
      };
    })
    // plugins/ also holds a README. Only folders with a manifest or a skill are plugins.
    .filter((p) => p.manifest || p.skills.length)
    .sort((a, b) => a.name.localeCompare(b.name));
}

// One entry per skill. Today a plugin holds exactly one skill, named like the plugin.
export function readSkills(root) {
  return readPlugins(root)
    .flatMap((p) => p.skills.map((s) => ({
      name: s.name,
      base: s.base,
      fm: s.fm,
      plugin: p.manifest,
      pluginName: p.name,
      pluginRoot: p.root,
    })))
    .sort((a, b) => a.name.localeCompare(b.name));
}
